//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Commands.DataFactories.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Commands.DataFactories.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove data factory &apos;{0}&apos; in resource group &apos;{1}&apos;?.
        /// </summary>
        internal static string DataFactoryConfirmationMessage {
            get {
                return ResourceManager.GetString("DataFactoryConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating data factory &apos;{0}&apos; in resource group &apos;{1}&apos;..
        /// </summary>
        internal static string DataFactoryCreating {
            get {
                return ResourceManager.GetString("DataFactoryCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data factory with the name {0} in the resource group {1} exists. 
        ///Continuing execution may overwrite the exisiting one. 
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string DataFactoryExists {
            get {
                return ResourceManager.GetString("DataFactoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data factory &apos;{0}&apos; does not exist in the resource group &apos;{1}&apos;..
        /// </summary>
        internal static string DataFactoryNotFound {
            get {
                return ResourceManager.GetString("DataFactoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing data factory &apos;{0}&apos; in resource group &apos;{1}&apos;..
        /// </summary>
        internal static string DataFactoryRemoving {
            get {
                return ResourceManager.GetString("DataFactoryRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name provided using -Name switch: &apos;{1}&apos; in cmdlet doesn&apos;t match with {0} name: &apos;{2}&apos; in JSON file. {0} will be created with name: &apos;{1}&apos;.
        /// </summary>
        internal static string ExtractedNameFromJsonMismatchWarning {
            get {
                return ResourceManager.GetString("ExtractedNameFromJsonMismatchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Status Code: {0}
        ///Error Code: {1}
        ///Error Message: {2}
        ///Request Id: {3}
        ///Timestamp (Utc):{4}.
        /// </summary>
        internal static string FormattedCloudExceptionMessageTemplate {
            get {
                return ResourceManager.GetString("FormattedCloudExceptionMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove linked service &apos;{0}&apos; in data factory &apos;{1}&apos;?.
        /// </summary>
        internal static string LinkedServiceConfirmationMessage {
            get {
                return ResourceManager.GetString("LinkedServiceConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating linked service &apos;{0}&apos; in data factory &apos;{1}&apos;..
        /// </summary>
        internal static string LinkedServiceCreating {
            get {
                return ResourceManager.GetString("LinkedServiceCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A linked service with the name {0} in the data factory {1} exists. 
        ///Continuing execution may overwrite the exisiting one. 
        ///Are you sure you want to continue?.
        /// </summary>
        internal static string LinkedServiceExists {
            get {
                return ResourceManager.GetString("LinkedServiceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked service &apos;{0}&apos; does not exist in the data factory &apos;{1}&apos;..
        /// </summary>
        internal static string LinkedServiceNotFound {
            get {
                return ResourceManager.GetString("LinkedServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing linked service &apos;{0}&apos; in data factory &apos;{1}&apos;..
        /// </summary>
        internal static string LinkedServiceRemoving {
            get {
                return ResourceManager.GetString("LinkedServiceRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource group name cannot be null..
        /// </summary>
        internal static string ResourceGroupNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ResourceGroupNameCannotBeEmpty", resourceCulture);
            }
        }
    }
}
